name: load_balance
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
#State Managent
  flutter_bloc: ^9.1.1

 # Helper tools for code simplification.
  equatable: ^2.0.7
  get_it: ^8.0.3 
  
#Router
  go_router: ^16.0.0
#Connection
  dartssh2: ^2.13.0
  ctelnet: ^0.3.1
  dio: ^5.8.0+1
  dart_ping: ^9.0.1

# --- Functional Programming ---
# For functional programming paradigms in Dart.
  fpdart: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
